include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false

linter:
    rules:
        - always_declare_return_types
        - always_require_non_null_named_parameters
        - always_specify_types
        - annotate_overrides
        - avoid_bool_literals_in_conditional_expressions
        - avoid_init_to_null
        - avoid_renaming_method_parameters
        - avoid_return_types_on_setters
        - avoid_returning_null_for_void
        - avoid_slow_async_io
        - avoid_types_as_parameter_names
        - avoid_unused_constructor_parameters
        - await_only_futures
        - camel_case_extensions
        - camel_case_types
        - cancel_subscriptions
        - hash_and_equals
        - implementation_imports
        - iterable_contains_unrelated_type
        - library_names
        - library_prefixes
        - list_remove_unrelated_type
        - no_duplicate_case_values
        - non_constant_identifier_names
        - overridden_fields
        - package_api_docs
        - package_names
        - package_prefixed_library_names
        - prefer_asserts_in_initializer_lists
        - prefer_contains
        - prefer_equal_for_default_values
        - prefer_single_quotes
        - prefer_typing_uninitialized_variables
        - recursive_getters
        - slash_for_doc_comments
        - test_types_in_equals
        - unnecessary_getters_setters
        - unnecessary_new
        - unrelated_type_equality_checks
        - valid_regexps
        - void_checks